/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux solimul-Zenbook-UP6502ZA-UP6502ZA 5.19.0-38-generic x86_64"
#define YALS_COMPILED "Thu 27 Apr 2023 10:09:08 PM MDT"
#define YALS_RELEASED "Fr 1. Mär 05:17:48 CET 2019"
#define YALS_VERSION "03v"
#define YALS_ID "b1316746d40f72f147cde3f4ec54fadbe0730427"
